# bundle.ps1
# 1. Concatenates every Lua module into dist/rogblox.lua
# 2. Generates launch-bundled.ps1 = launch.ps1 with the Base64-encoded
#    bundle baked in. That's what PS2EXE compiles into ROGBLOX.exe.

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path

$Modules = @(
    'src/library/ui.lua',
    'src/library/notify.lua',
    'src/library/savemanager.lua',
    'src/config.lua',
    'src/utils/players.lua',
    'src/utils/drawing.lua',
    'src/utils/env.lua',
    'src/modules/aimbot.lua',
    'src/modules/esp.lua',
    'src/modules/combat_extras.lua',
    'src/modules/movement.lua',
    'src/modules/teleport.lua',
    'src/modules/hud.lua',
    'src/modules/world.lua',
    'src/modules/autofarm.lua',
    'src/modules/misc.lua'
)
$Main = 'src/main.lua'

Write-Host '[*] Bundling Lua modules...' -ForegroundColor Cyan

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('-- ROGBLOX bundled distribution')
[void]$sb.AppendLine('-- Auto-generated by bundle.ps1 / bundle.py. Do not edit by hand.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('local _modules = {}')
[void]$sb.AppendLine('local _cache = {}')
[void]$sb.AppendLine('local function fetch(path)')
[void]$sb.AppendLine('    if _cache[path] ~= nil then return _cache[path] end')
[void]$sb.AppendLine('    local mod = _modules[path]')
[void]$sb.AppendLine('    if not mod then error("ROGBLOX bundle missing module: " .. tostring(path)) end')
[void]$sb.AppendLine('    _cache[path] = mod()')
[void]$sb.AppendLine('    return _cache[path]')
[void]$sb.AppendLine('end')
[void]$sb.AppendLine('')

foreach ($rel in $Modules) {
    $p = Join-Path $here $rel
    if (-not (Test-Path $p)) { throw "missing module: $rel" }
    $content = Get-Content -Raw -Path $p
    [void]$sb.AppendLine("_modules['$rel'] = function()")
    [void]$sb.AppendLine($content)
    [void]$sb.AppendLine('end')
    [void]$sb.AppendLine('')
}

$mainSrc = Get-Content -Raw -Path (Join-Path $here $Main)
# strip main.lua's HttpGet-based fetch; ours is provided above
$mainSrc = [regex]::Replace(
    $mainSrc,
    'local function fetch\(path\).*?return chunk\(\)\s*end\s*',
    "-- fetch provided by bundler`r`n",
    [Text.RegularExpressions.RegexOptions]::Singleline
)
[void]$sb.AppendLine($mainSrc)

$dist = Join-Path $here 'dist'
if (-not (Test-Path $dist)) { New-Item -ItemType Directory -Path $dist | Out-Null }
$outLua = Join-Path $dist 'rogblox.lua'
$sb.ToString() | Set-Content -Path $outLua -Encoding UTF8
$kb = [Math]::Round((Get-Item $outLua).Length / 1KB, 1)
Write-Host ("[+] Wrote $outLua ($kb KB, " + ($Modules.Count + 1) + ' files)') -ForegroundColor Green

# Inject Base64 of the bundle into launch.ps1 to produce launch-bundled.ps1
Write-Host '[*] Injecting bundle into launch-bundled.ps1...' -ForegroundColor Cyan

$bundleBytes = [System.IO.File]::ReadAllBytes($outLua)
$bundleB64   = [Convert]::ToBase64String($bundleBytes)

$launchSrc = Get-Content -Raw -Path (Join-Path $here 'launch.ps1')
if ($launchSrc -notmatch [regex]::Escape("`$EmbeddedScriptB64 = ''")) {
    throw 'launch.ps1 is missing the $EmbeddedScriptB64 placeholder.'
}
$bundled = $launchSrc -replace [regex]::Escape("`$EmbeddedScriptB64 = ''"),
                              ("`$EmbeddedScriptB64 = '" + $bundleB64 + "'")
$outPs1 = Join-Path $here 'launch-bundled.ps1'
$bundled | Set-Content -Path $outPs1 -Encoding UTF8
Write-Host ("[+] Wrote $outPs1") -ForegroundColor Green
