#!/usr/bin/env python3
"""
ROGBLOX bundler.

Concatenates every Lua module under src/ into a single self-contained
dist/rogblox.lua that has no external HTTP dependencies. The bundled
file can be dropped straight into an executor's autoexec folder and run
offline.

The Windows build pipeline mirrors this in bundle.ps1.
"""

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

MODULES = [
    "src/library/ui.lua",
    "src/library/notify.lua",
    "src/config.lua",
    "src/utils/players.lua",
    "src/utils/drawing.lua",
    "src/modules/aimbot.lua",
    "src/modules/esp.lua",
    "src/modules/combat_extras.lua",
    "src/modules/movement.lua",
    "src/modules/teleport.lua",
    "src/modules/hud.lua",
    "src/modules/world.lua",
    "src/modules/autofarm.lua",
    "src/modules/games.lua",
    "src/modules/playerlist.lua",
    "src/modules/console.lua",
    "src/modules/misc.lua",
]
MAIN = "src/main.lua"

HEADER = """-- ROGBLOX bundled distribution
-- Auto-generated by bundle.py / bundle.ps1. Do not edit by hand.

local _modules = {}
local _cache = {}
local function fetch(path)
    if _cache[path] ~= nil then return _cache[path] end
    local mod = _modules[path]
    if not mod then error("ROGBLOX bundle missing module: " .. tostring(path)) end
    _cache[path] = mod()
    return _cache[path]
end
"""


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def bundle() -> str:
    parts = [HEADER]
    for rel in MODULES:
        p = ROOT / rel
        if not p.exists():
            raise SystemExit(f"missing module: {rel}")
        src = read(p)
        parts.append(f"_modules[{rel!r}] = function()\n{src}\nend\n")

    main_src = read(ROOT / MAIN)
    # Strip the inline `local function fetch(path) ... end` block from
    # main.lua so our bundled fetch() takes over.
    main_src = re.sub(
        r"local function fetch\(path\).*?return chunk\(\)\s*end\s*\n",
        "-- fetch provided by bundler\n",
        main_src,
        count=1,
        flags=re.DOTALL,
    )
    parts.append(main_src)
    return "\n".join(parts)


def main() -> int:
    out_dir = ROOT / "dist"
    out_dir.mkdir(exist_ok=True)
    out_file = out_dir / "rogblox.lua"
    bundled = bundle()
    out_file.write_text(bundled, encoding="utf-8")
    size_kb = out_file.stat().st_size / 1024
    print(f"Bundled {len(MODULES) + 1} files -> {out_file} ({size_kb:.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
