#!/usr/bin/env python3
"""
Embed dist/rogblox.lua as a C byte array.

Called from CMakeLists.txt at configure time. Reads the input bundle
(positional arg 1), writes a self-contained C++ source (positional arg 2)
that defines `ROGBLOX_BUNDLE[]` and `ROGBLOX_BUNDLE_SIZE`. Much faster
than doing this in pure CMake string ops, which choke on large files.
"""

import sys
from pathlib import Path


HEADER = """// Auto-generated by cpp/loader/embed_bundle.py. Do not edit by hand.
// Embeds dist/rogblox.lua so the loader .exe is self-contained.
#include "bundle_data.hpp"

extern "C" const unsigned char ROGBLOX_BUNDLE[] = {
"""

FOOTER_FMT = "}};\nextern \"C\" const size_t ROGBLOX_BUNDLE_SIZE = {n};\n"


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("usage: embed_bundle.py <input.lua> <output.cpp>", file=sys.stderr)
        return 2
    inp = Path(argv[1])
    out = Path(argv[2])

    data = inp.read_bytes()

    lines: list[str] = [HEADER]
    BYTES_PER_LINE = 16
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i:i + BYTES_PER_LINE]
        lines.append("    " + ",".join("0x%02x" % b for b in chunk) + ",\n")
    lines.append(FOOTER_FMT.format(n=len(data)))

    out.write_text("".join(lines), encoding="utf-8")
    print("embed_bundle.py: wrote %s (%d bytes from %s)" % (
        out, len(data), inp))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
